# Generated by Django 5.0.6 on 2024-06-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_lead_message_remove_order_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='message',
        ),
    ]
